# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    
    # Configuration complète de la session
    session:
        enabled: true
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    # Autres configurations
    #esi: true
    #fragments: true

# Configuration spécifique pour l'environnement de test
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file